apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disc-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: fhm2ensob1je1lis4cpi
